#!bin/bash

rm -f kaninos/dists/stable/main/binary-amd64/Packag*
cd kaninos
apt-ftparchive -a amd64 packages pool/main > dists/stable/main/binary-amd64/Packages
gzip -k dists/stable/main/binary-amd64/Packages
xz -k dists/stable/main/binary-amd64/Packages
